name: flutter_3d_viewer
description: Package used to view 3d object in flutter
version: 1.0.0
homepage: https://github.com/mazab99/flutter_3d_viewer

environment:
  sdk: '>=2.17.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  vector_math: ^2.1.4

  path: ^1.8.3



dev_dependencies:
  flutter_test:
    sdk: flutter
